### ISSUE TITLE
Make Tatsu a sub-theme of Basis instead of forking the code

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tatsu#18]
@klonos asked in Gitter why I choose to fork the code from Basis rather than creating Tatsu as a sub theme of Basis. 

Initially, I just thought it would give me more control over the theme and I did not see a large benefit in making it a sub-theme. I think my experience in Drupal was was creating sub themes off of other contrib themes and I did not want to require users to install two different themes. But, because basis is in core - that distinction is not relevant. From a user point of view it will work the same as sub-theme or stand alone theme.

I am reconsidering my decision and may make Tatsu a sub theme of Basis. 

Comments?

**Comment by jenlampton** [comment]
I like the sub-theme idea, but selfishly because you may help us identify where things in Basis are too hard to override -- so we can fix them. :)

**Comment by stpaultim** [comment]
As someone involved in core development. I see the benefits of making it a sub theme of Basis.

**Comment by klonos** [comment]
Yup, I believe that making it a subtheme of Basis will allow inheriting bug fixes, UX improvements, and features. Otherwise, you'll have to cherry-pick any such changes and (re)implement them in Tatsu.

FTR (as also mentioned in the Gitter discussion), I think that the Tatsu layout that comes with the theme should be eventually split into a separate layout project, and then the theme and the layout should be made a dependency of each other (via `dependencies[]` in their .info files).

**Comment by stpaultim** [comment]
I went ahead and made it a sub-theme of basis and cut another release to reflect this change. 

I was not able to cut many files, because of the fact that I'm using the Color module and the color module currently rewrites pretty much the entire CSS directory, except new custom CSS provided by this theme. 

However, this does not need to be the case. Much of this CSS does not need to be touched by the color module and can be removed. I just need to keep the CSS effected by the color module.
