### ISSUE TITLE
Menu Dropdown Arrow appears as small dot

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/tatsu#61]
### Steps to reproduce

1. Start with a site with at least one page that has its menu entry as a child of the top level of the primary navigation
2. Install Tatsu 1.2 (might apply to released version but stopped using that) and set default
3. view menu

### Expected result
down arrow appears to right of menu item

### Actual result
small dot appears to right of menu item

![chrome_9Wo9OkN8VV](https://user-images.githubusercontent.com/20357797/152782502-94305e09-5543-46c9-982a-3f7b7a540484.gif)

### Cause
basis-component-colors.css is overriding the configured CSS.  Pull request to follow.

**Comment by Wylbur** [comment]
The directive in basis-component-color.css is supposed to update the color of the element.  The CSS used is instead replacing the arrow designation with a border that appears as a dot.  

Even with the reordering of the CSS element the problem still remains.  

Instead of assigning a border, we can just change the color of the element, which is the original intention of all these CSS overrides.  

So this element in basis-component-color.css:
`
.menu-dropdown a span.sub-arrow {
  border: 1px solid #bbbbbb;
}
`
changes to this:
`
.menu-dropdown a span.sub-arrow {
  border-color: #bbbbbb transparent transparent transparent;
}
`

Give that a try and let me know if that works.

**Comment by stpaultim** [comment]
@Wylbur Do you have time to fix this?
